Eliminate usage of with (python >= 2.6)
Compatibility with python 2.5 has not been officially dropped yet.

The squeeze packages still install python-m2ee to be used with python
2.5, despite python 2.6 being the default python version to run.

Byte-compiling the .py files with dh_python2 results in a warning
message printed during the apt-get run, which obviously is not handig.

Setting up python-m2ee (0.5.4-1~mxbp60+1) ...
/usr/lib/python2.5/site-packages/m2ee/config.py:378: Warning: 'with' will become a reserved keyword in Python 2.6
  File "/usr/lib/python2.5/site-packages/m2ee/config.py", line 378
    with open(felix_template_file) as input_file:
            ^
SyntaxError: invalid syntax