M2EEException: cause attribute
When catching an exception and wrapping it into an M2EEException (so it
can be specifically catched later on), provide an attribute to store the
original exception.