cli,config: Fix explode on reload without model
Right... When there's no unpacked application model, this just explodes:

File "/home/knorrie/s/m2ee-tools/src/m2ee/config.py", line 63, in __init__
  if self.runtime_version < 7:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

This is broken since commit e5fee3a4c7. Fix it by exiting the config
reload sequence when we already know it has no use to try to continue.

Also, if we attempt start without having an application model in place,
then don't complain about "the Mendix Runtime version which has to be
used" because we're not even that far yet.