M2EEException errno for runner
Instead of only doing M2EEException("Starting the JVM process did not
succeed..."), and having the detailed information in the logging
(instead of available in the program flow), the exception now have a
specific message and an errno.

start_appcontainer in core.py calls runner.start(), which does the
fork and exec magic to get the runtime process running in the
background. Every different failure scenario now has its own error code,
which a calling function can act on.

Also fix the handling of the return value of waitpid, which is a 16-bit
value, with the exit code in the higher 8 bits.

Test results:

Setting javabin to a non-existent file:
m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
ERROR: The java binary cannot be found in the default search path!
ERROR: By default, when starting the JVM, the environment is not
preserved. If you don't set preserve_environment to true or specify PATH
in preserve_environment or custom_environment in the m2ee section of
your m2ee.yaml configuration file, the search path is likely a very
basic default list like '/bin:/usr/bin'
ERROR: Starting the JVM process did not succeed: JVM binary not found,
errno: 0x201

Setting javabin to /etc/fstab:
m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
ERROR: Starting JVM failed: [Errno 13] Permission denied
ERROR: Starting the JVM process (fork/exec) did not succeed., errno:
0x202

Changing timeout in the code to 1 second:
m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
ERROR: Starting the JVM process takes too long., errno: 0x203
m2ee(knorrie): status
INFO: The application process is running, the MxRuntime has status: feut
ERROR: Executing get_logged_in_user_names did not succeed: result: -5,
message: Admin action 'get_logged_in_user_names' does not exist.
m2ee(knorrie): start
ERROR: There's already a MxRuntime process running, aborting start. If
the application is not functional, or failed to start earlier, try stop
or restart first., errno: 0x200

Setting javabin to /bin/true:
m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
ERROR: JVM process disappeared with a clean exit code., errno: 0x220

Setting javabin to /bin/false:
m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
ERROR: JVM process terminated without reason., errno: 0x221

m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
No permission to open socket or another server is already running on
localhost:5432: Address already in use
ERROR: JVM process terminated: could not bind admin port., errno: 0x222

m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
No permission to open socket or another server is already running on
port 5432: Address already in use
ERROR: JVM process terminated: could not bind runtime port., errno:
0x223

Note: The RUNTIME_PORT_IN_USE will only be seen with Mendix < 5. From 5
on, the runtime port settings moved to the
update_appcontainer_configuration admin api call.

For Mendix 5+, a non-specific M2EEAdminException is thrown, because the
wrong type of exception is used inside the runtime
(UpdateAppContainerConfigurationAction.java:78, AdminRuntimeException
with a process exit status code (probably copied from the old code),
instead of an AdminException with admin action specific error code):
ERROR: Executing update_appcontainer_configuration did not succeed:
result: 1, message: An unhandled exception occurred!, caused by: Runtime
port '5432' is already in use

m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
Invalid JVM version (OpenJDK Runtime Environment 1.6.0_37). Mendix
requires Java 7 to run your app. Please contact your system
administrator to get a valid Java version. Check the System Requirements
in the Mendix documentation for background information.
ERROR: JVM process terminated: incompatible JVM version., errno: 0x224