M2EEException errno ERR_START_ALREADY_RUNNING
Simplify the start flow a bit more. Since start_appcontainer is not
called over and over again any more when resolving startup errors, (also
see 19fc515736), there is no need to do anything when a JVM process is
already running, or when the admin API is accessible, which also means
something has already been started.

m2ee(knorrie): status
INFO: The application process is running, the MxRuntime has status: running
INFO: Logged in users: (0) []
m2ee(knorrie): start
ERROR: There's already a MxRuntime process running, aborting start. If
the application is not functional, or failed to start earlier, try stop
or restart first., errno: 0x200