M2EEException: introduce errno
An additional explicit error code can be provided so that the caller has
a more sane way to act on the specific error that occured, instead of
getting the exception and only having an error message inside.

m2ee(knorrie): start
ERROR: felix_config_file is not in a writable location: /, errno: 0x1