M2EEException errno ERR_MISSING_CONFIG
This code indicates that essential configuration to be able to start is
missing. When cleaning up the config handling later, this will be
reworked into more meaningful codes.

m2ee(knorrie): start
ERROR: Cannot start MxRuntime due to previous critical errors., errno: 0x101