Allow interactive database password input
If DatabasePassword is not set at all, allow setting it interactively.
This helps users who do not want to list a database password in a
configuration file. Obviously, it also breaks automated startup.

This replaces the former implementation of this feature, which was just
reverted. (see 0b219a46)

Current behaviour:

$ ./m2ee.py
WARNING: There is no database password present in the configuration. Either add it to the configuration, or use the set_database_password command to set it before trying to start the application!
m2ee(knorrie): start
ERROR: Executing start did not succeed: result: 1, message: DatabasePassword has no value
INFO: Waiting for the application to shutdown...
INFO: The application has been stopped successfully.
m2ee(knorrie): set_database_password
Database password:
m2ee(knorrie): start
INFO: Trying to start the MxRuntime...
INFO: The MxRuntime is fully started now.
m2ee(knorrie): psql
psql (9.4.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
database=#

Previous behaviour:

knorrie): start
INFO: Trying to start the MxRuntime...
Database password not configured, please provide now:
[...]

m2ee(knorrie): psql
Traceback (most recent call last):
  File "./m2ee.py", line 943, in <module>
    cli.cmdloop_handle_ctrl_c()
  File "./m2ee.py", line 809, in cmdloop_handle_ctrl_c
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "./m2ee.py", line 816, in onecmd
    return super(CLI, self).onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./m2ee.py", line 553, in do_psql
    pgutil.psql(self.m2ee.config)
  File "/home/knorrie/src/git/m2ee-tools/src/m2ee/pgutil.py", line 139, in psql
    env.update(config.get_pg_environment())
  File "/home/knorrie/src/git/m2ee-tools/src/m2ee/config.py", line 635, in get_pg_environment
    'PGPASSWORD': self._conf['mxruntime']['DatabasePassword'],
KeyError: 'DatabasePassword'