Abort startup when starting appcontainer fails.
This check was simply missing, resulting in unfamous errors like
AttributeError: 'NoneType' object has no attribute 'endswith'
when the requested runtime version is not available.