munin: don't log error when the app is not running
There's no need to fill up the logs with...

  ERROR: Admin API not available for requests:
  (<class 'ConnectionRefusedError'>: [Errno 111] Connection refused)

...if the app is just not running.